language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - nightly

sudo: false

before_install:
    - pip install --user codecov

before_script:
    - mysql -uroot -e "CREATE DATABASE excel_mysql_base CHARACTER SET utf8 COLLATE utf8_general_ci"
    - mysql -uroot -e "GRANT ALL PRIVILEGES ON excel_mysql_base.* TO 'user'@'localhost' IDENTIFIED BY 'pass'"

script:
    - phpunit --coverage-clover=coverage.xml

after_success:
    - codecov